#!/usr/bin/perl
use feature say;
use File::Slurp;

say "Reading template...";
$template = read_file "index.html" or die 'Cannot find index.html to read';

for (<*.html>) {
	next if /^index\.html$/; # Skip actual index page
	say "Compiling page $_...";
	$page = read_file $_;
	($content) = ($page =~ /(<!-- begin content -->.*<!-- end content -->)/ms);
	my $new_page = $template;
	$new_page =~ s/(<!-- begin content -->.*<!-- end content -->)/$content/ms;
	write_file($_, $new_page);
}
